export const products = [
  {
    id: '1',
    name: 'Hand-painted "Tree of Life" Kettle',
    price: 1800,
    imageUrl: 'https://picsum.photos/400/500?random=1',
    artisan: 'Ritu Kumar',
    category: 'Pottery',
    aiHint: 'painted kettle',
  },
  {
    id: '2',
    name: 'Kalamkari Hand-painted Saree',
    price: 5200,
    imageUrl: 'https://picsum.photos/400/500?random=2',
    artisan: 'Sanjay Chitara',
    category: 'Textiles',
    aiHint: 'indian saree',
  },
  {
    id: '3',
    name: 'Dhokra Brass Tortoise',
    price: 950,
    imageUrl: 'https://picsum.photos/400/500?random=3',
    artisan: 'Mina Devi',
    category: 'Jewelry',
    aiHint: 'brass sculpture',
  },
  {
    id: '4',
    name: 'Sandalwood Elephant Carving',
    price: 3500,
    imageUrl: 'https://picsum.photos/400/500?random=4',
    artisan: 'Gopal Sharma',
    category: 'Woodwork',
    aiHint: 'wood carving',
  },
  {
    id: '5',
    name: 'Pattachitra Scroll Painting',
    price: 4100,
    imageUrl: 'https://picsum.photos/400/500?random=5',
    artisan: 'Anika Das',
    category: 'Textiles',
    aiHint: 'scroll painting',
  },
  {
    id: '6',
    name: 'Jaipur Blue Pottery Vase',
    price: 1200,
    imageUrl: 'https://picsum.photos/400/500?random=6',
    artisan: 'Ramesh Prajapati',
    category: 'Pottery',
    aiHint: 'blue pottery',
  },
  {
    id: '7',
    name: 'Silver Filigree Peacock Earrings',
    price: 2800,
    imageUrl: 'https://picsum.photos/400/500?random=7',
    artisan: 'Priya Soni',
    category: 'Jewelry',
    aiHint: 'silver earrings',
  },
  {
    id: '8',
    name: 'Hand-carved Rosewood Spice Box',
    price: 2100,
    imageUrl: 'https://picsum.photos/400/500?random=8',
    artisan: 'Yusuf Bhai',
    category: 'Woodwork',
    aiHint: 'spice box',
  },
];

export const artisans = [
  {
    id: '1',
    name: 'Sanjay Chitara',
    craft: 'Mata ni Pachedi Textile Art',
    imageUrl: 'https://picsum.photos/400/400?random=9',
    aiHint: 'indian man',
    story:
      'For generations, my family has painted the stories of our goddesses on cloth. This art is our prayer, our history, and our livelihood. Each piece I create is a continuation of that sacred tradition.',
  },
  {
    id: '2',
    name: 'Ramesh Prajapati',
    craft: 'Jaipur Blue Pottery',
    imageUrl: 'https://picsum.photos/400/400?random=10',
    aiHint: 'artisan pottery',
    story:
      'The blue of my pottery is the blue of Jaipur skies. I mix quartz stone powder with my own hands, a technique that has been passed down to me. It is a slow, beautiful process that connects me to the earth.',
  },
];
